/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface SqliteDatabaseProperties {
  "key": string | null 
  "value": string | null 
}
export interface Attachment {
  "ROWID"?: number | null 
  "guid": string 
  "created_date": number | null 
  "start_date": number | null 
  "filename": string | null 
  "uti": string | null 
  "mime_type": string | null 
  "transfer_state": number | null 
  "is_outgoing": number | null 
  "user_info": any | null 
  "transfer_name": string | null 
  "total_bytes": number | null 
  "is_sticker": number | null 
  "sticker_user_info": any | null 
  "attribution_info": any | null 
  "hide_attachment": number | null 
  "ck_sync_state": number | null 
  "ck_server_change_token_blob": any | null 
  "ck_record_id": string | null 
  "original_guid": string 
  "sr_ck_sync_state": number | null 
  "sr_ck_server_change_token_blob": any | null 
  "sr_ck_record_id": string | null 
}
export interface Chat {
  "ROWID"?: number | null 
  "guid": string 
  "style": number | null 
  "state": number | null 
  "account_id": string | null 
  "properties": any | null 
  "chat_identifier": string | null 
  "service_name": string | null 
  "room_name": string | null 
  "account_login": string | null 
  "is_archived": number | null 
  "last_addressed_handle": string | null 
  "display_name": string | null 
  "group_id": string | null 
  "is_filtered": number | null 
  "successful_query": number | null 
  "engram_id": string | null 
  "server_change_token": string | null 
  "ck_sync_state": number | null 
  "original_group_id": string | null 
  "last_read_message_timestamp": number | null 
  "sr_server_change_token": string | null 
  "sr_ck_sync_state": number | null 
  "cloudkit_record_id": string | null 
  "sr_cloudkit_record_id": string | null 
  "last_addressed_sim_id": string | null 
  "is_blackholed": number | null 
}
export interface ChatHandleJoin {
  "chat_id": number | null 
  "handle_id": number | null 
}
export interface ChatMessageJoin {
  "chat_id"?: number | null 
  "message_id": number | null 
  "message_date": number | null 
}
export interface DeletedMessages {
  "ROWID"?: number | null 
  "guid": string 
}
export interface Handle {
  "ROWID"?: number | null 
  "id": string 
  "country": string | null 
  "service": string 
  "uncanonicalized_id": string | null 
  "person_centric_id": string | null 
}
export interface Kvtable {
  "ROWID"?: number | null 
  "key": string 
  "value": any 
}
export interface Message {
  "ROWID"?: number | null 
  "guid": string 
  "text": string | null 
  "replace": number | null 
  "service_center": string | null 
  "handle_id": number | null 
  "subject": string | null 
  "country": string | null 
  "attributedBody": any | null 
  "version": number | null 
  "type": number | null 
  "service": string | null 
  "account": string | null 
  "account_guid": string | null 
  "error": number | null 
  "date": number | null 
  "date_read": number | null 
  "date_delivered": number | null 
  "is_delivered": number | null 
  "is_finished": number | null 
  "is_emote": number | null 
  "is_from_me": number | null 
  "is_empty": number | null 
  "is_delayed": number | null 
  "is_auto_reply": number | null 
  "is_prepared": number | null 
  "is_read": number | null 
  "is_system_message": number | null 
  "is_sent": number | null 
  "has_dd_results": number | null 
  "is_service_message": number | null 
  "is_forward": number | null 
  "was_downgraded": number | null 
  "is_archive": number | null 
  "cache_has_attachments": number | null 
  "cache_roomnames": string | null 
  "was_data_detected": number | null 
  "was_deduplicated": number | null 
  "is_audio_message": number | null 
  "is_played": number | null 
  "date_played": number | null 
  "item_type": number | null 
  "other_handle": number | null 
  "group_title": string | null 
  "group_action_type": number | null 
  "share_status": number | null 
  "share_direction": number | null 
  "is_expirable": number | null 
  "expire_state": number | null 
  "message_action_type": number | null 
  "message_source": number | null 
  "associated_message_guid": string | null 
  "associated_message_type": number | null 
  "balloon_bundle_id": string | null 
  "payload_data": any | null 
  "expressive_send_style_id": string | null 
  "associated_message_range_location": number | null 
  "associated_message_range_length": number | null 
  "time_expressive_send_played": number | null 
  "message_summary_info": any | null 
  "ck_sync_state": number | null 
  "ck_record_id": string | null 
  "ck_record_change_tag": string | null 
  "destination_caller_id": string | null 
  "sr_ck_sync_state": number | null 
  "sr_ck_record_id": string | null 
  "sr_ck_record_change_tag": string | null 
  "is_corrupt": number | null 
  "reply_to_guid": string | null 
  "sort_id": number | null 
  "is_spam": number | null 
}
export interface MessageAttachmentJoin {
  "message_id": number | null 
  "attachment_id": number | null 
}
export interface MessageProcessingTask {
  "ROWID"?: number | null 
  "guid": string 
  "task_flags": number 
}
export interface SqliteStat1 {
  "tbl": any | null 
  "idx": any | null 
  "stat": any | null 
}
export interface SyncDeletedAttachments {
  "ROWID"?: number | null 
  "guid": string 
  "recordID": string | null 
}
export interface SyncDeletedChats {
  "ROWID"?: number | null 
  "guid": string 
  "recordID": string | null 
  "timestamp": number | null 
}
export interface SyncDeletedMessages {
  "ROWID"?: number | null 
  "guid": string 
  "recordID": string | null 
}

